version: '2'

volumes:
  data:

services:
  netrics:
    build: netrics/
    command: netrics control --continual
    network_mode: host
    volumes:
      - data:/tmp/results
    restart: always
    env_file:
      - variables.env

  server:
    build:
      context: uploads3/
    network_mode: host
    volumes:
      - data:/data
    env_file:
      - variables.env

