#!/usr/bin/env bash

SPEED_TARGETS="${LATENCY_TARGET-www.wikipedia.org} ${SPEED_TARGETS:-www.google.com}"
SPEED_REPS=${SPEED_REPS:-3}

tmpfile=$(mktemp)

for t in ${SPEED_TARGETS[*]};
do
    var=$(ping -D -c $SPEED_REPS $t | jc --ping)
    echo $var | jq --arg val "$t" '. += {target: $val}' >> $tmpfile
done

jq -s "." $tmpfile