[speed]
schedule = "0-59/10 * * * *"

[latencyload]
schedule = "5-59/10 * * * *"

[ping]
schedule = "*2-59/10 * * * *"

[ping.param]
destinations = [
    "google.com",
    "netflix.com",
    "nytimes.com",
    "facebook.com",
    "reddit.com",
    "github.com",
    "linkedin.com",
    "twitter.com",
]


