[speed]
schedule = "0-59/10 * * * *"

[latencyload]
schedule = "5-59/10 * * * *"
param = {target = "www.wikipedia.com", sleep_time = 3}

[bashping]
schedule = "2-59/10 * * * *"
param = {targets = ["google.com", "netflix.com", "nytimes.com"], reps = 3}
