[speed]
schedule = "*/3 * * * *"

[ping]
schedule = "*/1 * * * *"

[ping.param]
destinations = [
    "google.com",
    "netflix.com",
    "nytimes.com",
    "facebook.com",
    "reddit.com",
    "github.com",
    "linkedin.com",
    "twitter.com",
]


[traceroute]
schedule = "*/1 * * * *"

[traceroute.param]
targets = [
    "1.1.1.1",
    "nytimes.com",
]

