[speed]
schedule = "0-59/10 * * * *"

[latencyload]
schedule = "5-59/10 * * * *"

[latencyload.param]
target = "www.wikipedia.com"
sleep_time = 3

[bashping]
schedule = "*2-59/10 * * * *"

[bash.param]
targets = [
    "google.com",
    "netflix.com",
    "nytimes.com",
    "facebook.com",
    "reddit.com",
    "github.com",
    "linkedin.com",
    "twitter.com",
]
reps = 3



